### ISSUE TITLE
Renderer should not access DB

### ISSUE THREAD

**Issue by mudrd8mz** [unikent/moodle-tool_adhoc#17]
The `tool_adhoc_renderer::adhoc_tasks_table()` should receive all data to render via parameters, it itself should not access $DB. I know this pattern is often violated but because I can see the code is otherwise very clean and modern, I was thinking you might want to have this improved, too :-)

**Comment by sk-unikent** [comment]
Thanks for the suggestion! Fixed in https://github.com/unikent/moodle-tool_adhoc/commit/e18d151b42ae156fba3bee6c9e508550f643ec42
